CREATE TABLE NumberData(
  no INT(11) NOT NULL AUTO_INCREMENT,
  num1 INT(11) NOT NULL,
  num2 INT(11) NOT NULL,
  num3 INT(11) NOT NULL,
  num4 INT(11) NOT NULL,
  num5 INT(11) NOT NULL,
  num6 INT(11) NOT NULL,
  pickDate DATETIME DEFAULT NULL,
  times INT(11) NOT NULL,
  rank INT(11) DEFAULT NULL,
  memberId VARCHAR (50) NOT NULL,
  PRIMARY KEY(no)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE WinNumberData(
  num1 INT(11) DEFAULT NULL,
  num2 INT(11) DEFAULT NULL,
  num3 INT(11) DEFAULT NULL,
  num4 INT(11) DEFAULT NULL,
  num5 INT(11) DEFAULT NULL,
  num6 INT(11) DEFAULT NULL,
  bonusNum INT(11) DEFAULT NULL,
  times INT(11) NOT NULL,
  PRIMARY KEY(times)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;