CREATE TABLE postData(
  postNo INT (11) DEFAULT NULL NOT NULL AUTO_INCREMENT,
  boardNo INT (11) DEFAULT NULL,
  postName VARCHAR (50) DEFAULT NULL,
  postingDate DATETIME DEFAULT NULL,
  modifyDate DATETIME DEFAULT NULL,
  postedId VARCHAR (50) DEFAULT NULL,
  viewCnt INT (11) DEFAULT NULL,
  commentCnt INT (11) DEFAULT NULL,
  PRIMARY KEY (postNo)
) ENGINE=InnoDB DEFAULT CHARSET=utf8